import {
  project1Laptop,
  project1Mobile,
  project2Laptop,
  project2Mobile,
  project3Laptop,
  project3Mobile,
  project4Laptop,
  project4Mobile,
  project5Laptop,
  project5Mobile,
  project6Laptop,
  project6Mobile,
} from "./projectImages";

export const projectData = [
  {
    id: 1,
    image: project1Laptop,
    transitionImage: project1Mobile,
    title: "King Plexi",
    codeLink: "https://github.com/fatihyanik/meditation-app",
    liveLink: "https://king-plexi.vercel.app/",
  },
  {
    id: 2,
    image: project2Laptop,
    transitionImage: project2Mobile,
    title: "World Of Shoes",
    codeLink: "https://github.com/fatihyanik/Shoes_Project",
    liveLink: "https://world-of-shoes.netlify.app/",
  },
  {
    id: 3,
    image: project3Laptop,
    transitionImage: project3Mobile,
    title: "Turkey Parallax",
    codeLink: "https://github.com/fatihyanik/TurkeyParallax",
    liveLink: "https://turkeyparallax.netlify.app/",
  },
  {
    id: 4,
    image: project4Laptop,
    transitionImage: project4Mobile,
    title: "Personal Note App",
    codeLink: "https://github.com/fatihyanik/notesapp",
    liveLink: "https://fatih-note-app.netlify.app/",
  },
  {
    id: 5,
    image: project5Laptop,
    transitionImage: project5Mobile,
    title: "Blog Website",
    codeLink: "https://github.com/fatihyanik/react-final-project",
    liveLink: "https://react-heroku-react-final.herokuapp.com/",
  },
  {
    id: 6,
    image: project6Laptop,
    transitionImage: project6Mobile,
    title: "Expense Tracker",
    codeLink: "https://github.com/fatihyanik/expense-tracker-react",
    liveLink: "https://react-expense-tracker-mfy.herokuapp.com/",
  },
];
